app:
  encoding: @project.build.sourceEncoding@
  java:
    version: @java.version@
server:
  port: 8081
  servlet:
    contextPath: /admin
  undertow:
    io-threads: 1
    worker-threads: 2
    buffer-size: 1024
    buffers-per-region: 1024
    direct-buffers: true
spring:
  mvc:
    static-path-pattern: /**
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/jken
    username: sa
    password: sa
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: blah
      maximum-pool-size: 2
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  messages:
    basename: i18n/message
  data:
    web:
      pageable:
        one-indexed-parameters: true
        page-parameter: page
        size-parameter: limit
  quartz:
    jobStoreType: JDBC
  thymeleaf:
    cache: false